# Notebook 2 — Data Inspection

**Sprint 4**

**Dataset:** Telecom Customer Churn Dataset (`telecom_customer_churn.csv`) —
see `01_Dataset_Understanding.ipynb` for full documentation.

In this notebook we inspect the dataset in detail using core pandas
functions, and classify each column by type (numerical, categorical,
date/time, identifier, target).

In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
df = pd.read_csv('telecom_customer_churn.csv')
df.head()

,customer_id,gender,senior_citizen,partner,dependents,tenure_months,phone_service,internet_service,contract,paperless_billing,payment_method,monthly_charges,total_charges,churn
0,CUST-10681,Male,0,Yes,No,24.0,Yes,Fiber optic,Month-to-month,Yes,Credit card,80.04,1900.19,No
1,CUST-10024,Female,0,Yes,No,35.0,Yes,Fiber optic,Month-to-month,Yes,Mailed check,42.99,1539.83,No
2,CUST-10621,Male,0,Yes,No,68.0,Yes,DSL,Month-to-month,Yes,Electronic check,79.31,5401.35,Yes
3,CUST-10099,Male,0,Yes,Yes,18.0,Yes,Fiber optic,Month-to-month,Yes,Electronic check,113.02,2022.80,No
4,CUST-10284,Male,1,Yes,Yes,34.0,Yes,No,Month-to-month,No,Electronic check,28.78,966.99,Yes

## 1. Number of Rows and Number of Columns

We can get the number of rows and columns using `shape`, or individually
with `len(df)` and `len(df.columns)`.

In [2]:
num_rows, num_cols = df.shape
print("Number of rows   :", num_rows)
print("Number of columns:", num_cols)

Number of rows   : 1015
Number of columns: 14

## 2. `shape`

`df.shape` returns a tuple `(rows, columns)` describing the dataset's
dimensions in one call.

In [3]:
df.shape

(1015, 14)

## 3. Data Types (`dtypes`)

`df.dtypes` shows the data type pandas has inferred for every column
(e.g. `int64`, `float64`, `object` for text).

In [4]:
df.dtypes

customer_id              str
gender                   str
senior_citizen         int64
partner                  str
dependents               str
tenure_months        float64
phone_service            str
internet_service         str
contract                 str
paperless_billing        str
payment_method           str
monthly_charges      float64
total_charges        float64
churn                    str
dtype: object

## 4. Column Names

`df.columns` gives the list of all column names in the dataset.

In [5]:
df.columns.tolist()

['customer_id',
 'gender',
 'senior_citizen',
 'partner',
 'dependents',
 'tenure_months',
 'phone_service',
 'internet_service',
 'contract',
 'paperless_billing',
 'payment_method',
 'monthly_charges',
 'total_charges',
 'churn']

## 5. Index

The **index** is the label for each row. By default, pandas assigns a
simple integer index (0, 1, 2, ...) when a CSV is read.

In [6]:
df.index

RangeIndex(start=0, stop=1015, step=1)

## 6. `head()`

`head(n)` shows the **first n rows** of the dataset (default 5). Useful for
a quick first look at the data.

In [7]:
df.head()

,customer_id,gender,senior_citizen,partner,dependents,tenure_months,phone_service,internet_service,contract,paperless_billing,payment_method,monthly_charges,total_charges,churn
0,CUST-10681,Male,0,Yes,No,24.0,Yes,Fiber optic,Month-to-month,Yes,Credit card,80.04,1900.19,No
1,CUST-10024,Female,0,Yes,No,35.0,Yes,Fiber optic,Month-to-month,Yes,Mailed check,42.99,1539.83,No
2,CUST-10621,Male,0,Yes,No,68.0,Yes,DSL,Month-to-month,Yes,Electronic check,79.31,5401.35,Yes
3,CUST-10099,Male,0,Yes,Yes,18.0,Yes,Fiber optic,Month-to-month,Yes,Electronic check,113.02,2022.80,No
4,CUST-10284,Male,1,Yes,Yes,34.0,Yes,No,Month-to-month,No,Electronic check,28.78,966.99,Yes

In [8]:
df.head(10)

,customer_id,gender,senior_citizen,partner,dependents,tenure_months,phone_service,internet_service,contract,paperless_billing,payment_method,monthly_charges,total_charges,churn
0,CUST-10681,Male,0,Yes,No,24.0,Yes,Fiber optic,Month-to-month,Yes,Credit card,80.04,1900.19,No
1,CUST-10024,Female,0,Yes,No,35.0,Yes,Fiber optic,Month-to-month,Yes,Mailed check,42.99,1539.83,No
2,CUST-10621,Male,0,Yes,No,68.0,Yes,DSL,Month-to-month,Yes,Electronic check,79.31,5401.35,Yes
3,CUST-10099,Male,0,Yes,Yes,18.0,Yes,Fiber optic,Month-to-month,Yes,Electronic check,113.02,2022.80,No
4,CUST-10284,Male,1,Yes,Yes,34.0,Yes,No,Month-to-month,No,Electronic check,28.78,966.99,Yes
5,CUST-10691,Female,0,No,No,49.0,Yes,Fiber optic,Month-to-month,Yes,Mailed check,51.32,2502.45,No
6,CUST-10744,Female,0,Yes,No,63.0,Yes,Fiber optic,Month-to-month,Yes,Credit card,75.87,4776.31,No
7,CUST-10308,Male,0,Yes,No,NaN,No,Fiber optic,Month-to-month,Yes,Mailed check,55.82,1554.02,Yes
8,CUST-10769,male,0,Yes,No,14.0,Yes,Fiber optic,Month-to-month,Yes,Electronic check,26.06,312.41,Yes
9,CUST-10435,Male,0,No,No,0.0,Yes,DSL,One year,No,Credit card,97.97,0.00,No

## 7. `tail()`

`tail(n)` shows the **last n rows** of the dataset (default 5).

In [9]:
df.tail()

,customer_id,gender,senior_citizen,partner,dependents,tenure_months,phone_service,internet_service,contract,paperless_billing,payment_method,monthly_charges,total_charges,churn
1010,CUST-10579,Male,0,Yes,No,31.0,Yes,Fiber optic,Two year,No,Electronic check,34.00,1079.58,No
1011,CUST-10502,Female,0,Yes,No,37.0,Yes,Fiber optic,One year,Yes,Credit card,34.52,1243.58,No
1012,CUST-10537,Male,0,Yes,No,69.0,Yes,DSL,Month-to-month,No,Credit card,114.79,7927.64,Yes
1013,CUST-10196,Male,0,Yes,Yes,45.0,Yes,Fiber optic,Month-to-month,Yes,Bank transfer,81.72,3664.30,No
1014,CUST-10175,Male,0,No,No,33.0,Yes,DSL,Two year,Yes,Credit card,109.12,3621.04,No

## 8. `sample()`

`sample(n)` returns **n random rows**, which is useful to get an unbiased
peek at the data (unlike `head()`/`tail()` which only show the edges).

In [10]:
df.sample(5, random_state=1)

,customer_id,gender,senior_citizen,partner,dependents,tenure_months,phone_service,internet_service,contract,paperless_billing,payment_method,monthly_charges,total_charges,churn
920,CUST-10841,Female,0,Yes,No,62.0,Yes,DSL,Two year,Yes,Bank transfer,32.01,2018.32,No
619,CUST-10254,Female,0,Yes,No,18.0,Yes,No,Month-to-month,Yes,Bank transfer,88.16,1588.83,No
293,CUST-10264,Female,1,No,No,39.0,Yes,Fiber optic,Month-to-month,Yes,Credit card,85.92,3359.92,No
507,CUST-10968,Female,0,No,No,39.0,No,Fiber optic,Two year,No,Bank transfer,111.12,4374.12,Yes
975,CUST-10763,Female,1,No,No,63.0,Yes,No,One year,Yes,Electronic check,85.88,5401.13,Yes

## 9. `info()`

`info()` gives a concise summary of the dataframe: number of entries, column
names, non-null counts (helps spot missing values), data types, and memory
usage.

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1015 entries, 0 to 1014
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        1015 non-null   str
 1   gender             1015 non-null   str
 2   senior_citizen     1015 non-null   int64
 3   partner            1015 non-null   str
 4   dependents         1015 non-null   str
 5   tenure_months      1005 non-null   float64
 6   phone_service      1015 non-null   str
 7   internet_service   995 non-null    str
 8   contract           1015 non-null   str
 9   paperless_billing  1015 non-null   str
 10  payment_method     1000 non-null   str
 11  monthly_charges    1015 non-null   float64
 12  total_charges      985 non-null    float64
 13  churn              1015 non-null   str
dtypes: float64(3), int64(1), str(10)
memory usage: 168.7 KB

**Observation:** Columns like `tenure_months`, `internet_service`,
`payment_method`, and `total_charges` show fewer non-null entries than the
total row count — this indicates **missing values**, a data-quality issue
we will handle in a later sprint (data cleaning).

## 10. `describe()`

`describe()` generates summary statistics. By default it covers only
**numerical columns** (count, mean, std, min, quartiles, max).

In [12]:
df.describe()

       senior_citizen  tenure_months  monthly_charges  total_charges
count     1015.000000    1005.000000      1015.000000     985.000000
mean         0.178325      34.259701        69.294039    2360.987442
std          0.382975      21.137597        30.125169    1883.592371
min          0.000000       0.000000       -97.930000       0.000000
25%          0.000000      16.000000        44.395000     867.590000
50%          0.000000      34.000000        70.090000    1849.210000
75%          0.000000      52.000000        94.370000    3486.550000
max          1.000000      72.000000       119.450000    8354.360000

We can pass `include='object'` to get summary statistics for
**categorical (text) columns** instead — count, number of unique values,
the most frequent value (`top`), and its frequency (`freq`).

In [13]:
df.describe(include='object')

C:\Users\hemak\AppData\Local\Temp\ipykernel_384\87514550.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include='object')

,customer_id,gender,partner,dependents,phone_service,internet_service,contract,paperless_billing,payment_method,churn
count,1015,1015,1015,1015,1015,995,1015,1015,1000,1015
unique,1000,6,6,2,2,3,3,6,4,2
top,CUST-10345,Female,No,No,Yes,Fiber optic,Month-to-month,Yes,Bank transfer,No
freq,2,498,501,700,916,431,559,604,268,697

**Observation:** `describe()` on numerical columns shows a **negative
minimum value for `monthly_charges`**, which is not realistic (charges
cannot be negative) — this is a data-entry error we intentionally kept in
this dataset to demonstrate a real-world data-quality issue.

## 11. `dtypes` (Column-wise Recap)

Let's look at `dtypes` again, alongside the number of missing values per
column, for a combined view.

In [14]:
pd.DataFrame({
    'dtype': df.dtypes,
    'missing_values': df.isnull().sum(),
    'missing_percent': (df.isnull().sum() / len(df) * 100).round(2)
})

                     dtype  missing_values  missing_percent
customer_id            str               0             0.00
gender                 str               0             0.00
senior_citizen       int64               0             0.00
partner                str               0             0.00
dependents             str               0             0.00
tenure_months      float64              10             0.99
phone_service          str               0             0.00
internet_service       str              20             1.97
contract               str               0             0.00
paperless_billing      str               0             0.00
payment_method         str              15             1.48
monthly_charges    float64               0             0.00
total_charges      float64              30             2.96
churn                  str               0             0.00

## 12. `nunique()`

`nunique()` returns the **number of unique values** in each column. This
helps distinguish identifier columns (all unique), categorical columns (few
unique values), and numerical columns (many unique values).

In [15]:
df.nunique().sort_values()

senior_citizen          2
dependents              2
phone_service           2
churn                   2
contract                3
internet_service        3
payment_method          4
gender                  6
partner                 6
paperless_billing       6
tenure_months          73
monthly_charges       955
total_charges         962
customer_id          1000
dtype: int64

## 13. `value_counts()`

`value_counts()` shows the **frequency of each unique value** in a column —
extremely useful for understanding the distribution of categorical columns
(and for spotting inconsistent labels, e.g. `'Yes'` vs `'yes'` vs `'Y'`).

In [16]:
df['churn'].value_counts()

churn
No     697
Yes    318
Name: count, dtype: int64

In [17]:
df['contract'].value_counts()

contract
Month-to-month    559
One year          249
Two year          207
Name: count, dtype: int64

In [18]:
df['gender'].value_counts()

gender
Female    498
Male      490
female      9
F           7
M           7
male        4
Name: count, dtype: int64

In [19]:
df['partner'].value_counts()

partner
No     501
Yes    492
yes      7
Y        7
N        5
no       3
Name: count, dtype: int64

## 14. Column Classification

Based on the inspection above, we classify every column into a category.

| Column | Type | Notes |
|---|---|---|
| `customer_id` | **Identifier** | Unique (or near-unique) label per row; not used as a model feature |
| `gender` | Categorical | 2 main categories, with some inconsistent spelling variants (data-quality issue) |
| `senior_citizen` | Numerical (Discrete) | Only takes values 0 or 1 (flag) |
| `partner` | Categorical | Yes/No, with some inconsistent spelling variants |
| `dependents` | Categorical | Yes/No |
| `tenure_months` | Numerical (Discrete) | Whole number of months; has some missing values |
| `phone_service` | Categorical | Yes/No |
| `internet_service` | Categorical | DSL / Fiber optic / No; has some missing values |
| `contract` | Categorical | Month-to-month / One year / Two year |
| `paperless_billing` | Categorical | Yes/No |
| `payment_method` | Categorical | 4 payment types; has some missing values |
| `monthly_charges` | Numerical (Continuous) | Contains a data-entry error (negative values) |
| `total_charges` | Numerical (Continuous), stored as **text (object)** | Needs type conversion; has missing values |
| `churn` | Categorical — **Target Variable** | Yes/No — what we want to predict |

**No date/time columns** are present in this dataset (this dataset does not
track signup dates or timestamps — it uses `tenure_months` as a proxy for
customer duration instead).

### Column Groups Summary

In [20]:
identifier_columns = ['customer_id']
target_column = ['churn']
numerical_columns = ['senior_citizen', 'tenure_months', 'monthly_charges', 'total_charges']
categorical_columns = ['gender', 'partner', 'dependents', 'phone_service',
                        'internet_service', 'contract', 'paperless_billing',
                        'payment_method']
datetime_columns = []  
print("Identifier column(s) :", identifier_columns)
print("Target column        :", target_column)
print("Numerical columns    :", numerical_columns)
print("Categorical columns  :", categorical_columns)
print("Date/time columns    :", datetime_columns if datetime_columns else "None present in this dataset")
assert len(identifier_columns) + len(target_column) + len(numerical_columns) + len(categorical_columns) == df.shape[1]
print("\nColumn classification accounts for all", df.shape[1], "columns. ✔")

Identifier column(s) : ['customer_id']
Target column        : ['churn']
Numerical columns    : ['senior_citizen', 'tenure_months', 'monthly_charges', 'total_charges']
Categorical columns  : ['gender', 'partner', 'dependents', 'phone_service', 'internet_service', 'contract', 'paperless_billing', 'payment_method']
Date/time columns    : None present in this dataset

Column classification accounts for all 14 columns. ✔

## 15. Data-Quality Issues Identified During Inspection

Summary of the realistic issues found while inspecting this dataset (to be
addressed in a future data-cleaning sprint):

1. **Missing values** in `tenure_months`, `internet_service`,
   `payment_method`, and `total_charges` (seen via `info()` and
   `isnull().sum()`).
2. **Wrong data type** — `total_charges` is stored as `object` (text)
   instead of a numeric type, partly due to stray leading spaces.
3. **Inconsistent categorical labels** — e.g. `gender` contains
   `'Male'`, `'M'`, `'male'` as separate values instead of one consistent
   label (seen via `value_counts()`).
4. **Duplicate rows** — some customer records appear more than once
   (seen via `nunique()` on `customer_id` being less than total row count).
5. **Invalid values** — `monthly_charges` contains a few negative values,
   which is not physically meaningful for a charge amount (seen via
   `describe()`).

In [21]:
print("Duplicate rows in dataset:", df.duplicated().sum())
print("Rows with negative monthly_charges:", (df['monthly_charges'] < 0).sum())

Duplicate rows in dataset: 15
Rows with negative monthly_charges: 3